version: "3"
services:
  redis:
    image: "redis:alpine"
    restart: always
    ports:
      - "6379:6379"

  fpl-md:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src/fpl_md/db:/app/src/fpl_md/db
    restart: always
    links:
      - redis
