version: "3"
services:
  redis:
    image: "redis:alpine"
    restart: always
    ports:
      - "6379:6379"

  fpl-md:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    links:
      - redis
